name: CD - Deploy to Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Frontend
        run: |
          cd front
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp:frontend-latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp:frontend-latest

      - name: Build & Push Backend
        run: |
          cd back
          docker build -t ${{ secrets.DOCKER_USERNAME }}/bobapp:backend-latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/bobapp:backend-latest
